sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - export HAVERSION=$(curl https://api.github.com/repos/home-assistant/home-assistant/releases/latest|jq -r .name)
        - sed -i "s/_HAVERSIONi_/${HAVERSION}/g" Dockerfile
        - docker build -t mansm/home-assistant:${HAVERSION} .
