version: "3.1"
services:
  traefik:
    image: traefik:1.5
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    container_name: traefik
  
  hass:
    image: "mansm/homeassistant:latest"
    #container_name: homeassistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/root/.homeassistant
    ports:
      - 8123:8123
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    network_mode: host 
    #networks:
    #  - web
    #  - mqtt
    labels:
      traefik.backend: mansm.io
      traefik.docker.network: web
      traefik.frontend.rule: Host:home.mansm.io
      traefik.enable: "true"
      traefik.port: "8123"
      traefik.default.protocol: http
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyS0"
      - "/dev/vhci:/dev/vhci"
  
  mqtt:
    image: mansm/mqtt
    ports:
      - 1883:1883

networks:
  web:
    external: true
  mqtt:
